
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The personal site for Jet 'Jetroid' Holt
baseurl: "" # the subpath of your site, e.g. /blog
url: "jetroid.github.io" # the base hostname & protocol for your site
github_username:  jetroid

# Build settings
markdown: kramdown
