title: Jetroid!!
description: The personal site for Jet 'Jetroid' Holt
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jetholt.com" # the base hostname & protocol for your site

permalink: :title/

paginate: 10
paginate_path: "/page:num/"

collections:
  timeline:
    output: false
  category:
    output: true
  trips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: category
  -
    scope:
      path: "old-terminal/*"
    values:
      sitemap: false

# Build settings
markdown: kramdown
compress_html:
  comments: all
  clippings: all
sass:
  style: compressed
#Jekyll Sitemap must come after any gems which generate content
#gems which come after sitemap will not be included in the sitemap
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate

# Style settings - will be used in css
style:
    text: "#cfcfc9"
    highlight: "#d05d5d"
    background-rgb: "55, 55, 49,"
    background-hex: "#373731"

#Do not index oldstuff
exclude:
  - oldstuff
  - about.md
  - assets/images/content/compressed.md
  - assets/images/backgrounds/compressed.md
  - assets/images/compressed.md
