title: Jetroid
description: The personal site for Jet 'Jetroid' Holt
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jetholt.com" # the base hostname & protocol for your site

permalink: :title/

paginate: 10
paginate_path: "/page:num/"

calltoaction: "I'm late to the party, but I recently got <a href='https://twitter.com/JetroidMakes'>a twitter account</a> that you can follow <a href='https://twitter.com/intent/user?screen_name=JetroidMakes'>here</a>."

collections:
  timeline:
    output: false
  category:
    output: true
  trips:
    output: false
  micro:
    output: true
    permalink: micro/:title/
  projects:
    output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: category
  -
    scope:
      path: "old-terminal/*"
    values:
      sitemap: false
  -
    scope:
      path: ""
      type: micro
    values:
      layout: post
      includemailchimp: false

# Build settings
markdown: kramdown
compress_html:
  comments: all
  clippings: all
  ignore:
    envs: ["development"]
sass:
  sass_dir: /_includes/inlinecss/_sass
  style: compressed

#Jekyll Sitemap must come after any gems which generate content
#gems which come after sitemap will not be included in the sitemap
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-include-cache

# Style settings - not actually used but good for ease of reference
style:
    white-text: "#cfcfc9"
    pink-text: "#d05d5d"
    cyan-paint: "#94cbc4"
    grey-rgb: "55, 55, 49,"
    grey-hex: "#373731"

#Do not index oldstuff
exclude:
  - oldstuff
  - about.md
  - assets/images/content/compressed.md
  - assets/images/backgrounds/compressed.md
  - assets/images/compressed.md
  - Gemfile
  - Gemfile.lock
  - optimimage.py
  - Rakefile
  - .gitignore
